name: blabla
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-74.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  event_bus: ^2.0.0
  path_provider: ^2.1.3
  permission_handler: ^6.1.3
  replay_kit_launcher: ^1.0.0
  intl: ^0.19.0
  tencent_trtc_cloud: ^2.7.8

  crypto: ^3.0.3
  ionicons: ^0.2.2
  firebase_auth: ^4.19.2
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  tflite_audio: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
