name: blabla
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-74.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2

  cupertino_icons: ^1.0.6

  event_bus: ^2.0.0
  path_provider: ^2.1.3
  replay_kit_launcher: ^1.0.0
  intl: ^0.20.2

  crypto: ^3.0.3
  ionicons: ^0.2.2
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  permission_handler: ^12.0.0+1
  tencent_trtc_cloud: ^3.0.0
  flutter_sound: ^9.28.0
  tflite_flutter: ^0.11.0
  iconsax: ^0.0.8
  collection: ^1.19.0
  image: ^4.5.4
#  tflite_audio: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/GilroyMedium.ttf
        - asset: fonts/GilroyRegular.ttf
          weight: 100
        - asset: fonts/GilroyMedium.ttf
          weight: 400
        - asset: fonts/GilroyBold.ttf
          weight: 700
        - asset: fonts/GilroySemiBold.ttf
          weight: 500